/*
 * Medical System API
 * API для управління лікарями та записами на прийом у медичній системі.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DoctorContactInfo model module.
 * @module model/DoctorContactInfo
 * @version 1.0.0
 */
export default class DoctorContactInfo {
  /**
   * Constructs a new <code>DoctorContactInfo</code>.
   * Контактна інформація лікаря
   * @alias module:model/DoctorContactInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DoctorContactInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DoctorContactInfo} obj Optional instance to populate.
   * @return {module:model/DoctorContactInfo} The populated <code>DoctorContactInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DoctorContactInfo();
      if (data.hasOwnProperty('phone'))
        obj.phone = ApiClient.convertToType(data['phone'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
    }
    return obj;
  }
}

/**
 * Номер телефону лікаря
 * @member {String} phone
 */
DoctorContactInfo.prototype.phone = undefined;

/**
 * Електронна адреса лікаря
 * @member {String} email
 */
DoctorContactInfo.prototype.email = undefined;

