/*
 * Medical System API
 * API для управління лікарями та записами на прийом у медичній системі.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import DoctorAvailability from './DoctorAvailability';
import DoctorContactInfo from './DoctorContactInfo';

/**
 * The Doctor model module.
 * @module model/Doctor
 * @version 1.0.0
 */
export default class Doctor {
  /**
   * Constructs a new <code>Doctor</code>.
   * @alias module:model/Doctor
   * @class
   * @param name {String} Ім'я та прізвище лікаря
   * @param speciality {String} Медична спеціальність лікаря
   * @param contactInfo {module:model/DoctorContactInfo} 
   */
  constructor(name, speciality, contactInfo) {
    this.name = name;
    this.speciality = speciality;
    this.contactInfo = contactInfo;
  }

  /**
   * Constructs a <code>Doctor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Doctor} obj Optional instance to populate.
   * @return {module:model/Doctor} The populated <code>Doctor</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Doctor();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('speciality'))
        obj.speciality = ApiClient.convertToType(data['speciality'], 'String');
      if (data.hasOwnProperty('contact_info'))
        obj.contactInfo = DoctorContactInfo.constructFromObject(data['contact_info']);
      if (data.hasOwnProperty('availability'))
        obj.availability = ApiClient.convertToType(data['availability'], [DoctorAvailability]);
      if (data.hasOwnProperty('education'))
        obj.education = ApiClient.convertToType(data['education'], ['String']);
      if (data.hasOwnProperty('certificates'))
        obj.certificates = ApiClient.convertToType(data['certificates'], ['String']);
    }
    return obj;
  }
}

/**
 * Унікальний ідентифікатор лікаря
 * @member {Number} id
 */
Doctor.prototype.id = undefined;

/**
 * Ім'я та прізвище лікаря
 * @member {String} name
 */
Doctor.prototype.name = undefined;

/**
 * Медична спеціальність лікаря
 * @member {String} speciality
 */
Doctor.prototype.speciality = undefined;

/**
 * @member {module:model/DoctorContactInfo} contactInfo
 */
Doctor.prototype.contactInfo = undefined;

/**
 * Графік роботи лікаря
 * @member {Array.<module:model/DoctorAvailability>} availability
 */
Doctor.prototype.availability = undefined;

/**
 * Перелік навчальних закладів та отриманих ступенів
 * @member {Array.<String>} education
 */
Doctor.prototype.education = undefined;

/**
 * Перелік отриманих сертифікатів та ліцензій
 * @member {Array.<String>} certificates
 */
Doctor.prototype.certificates = undefined;

