/*
 * Medical System API
 * API для управління лікарями та записами на прийом у медичній системі.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The DoctorAvailability model module.
 * @module model/DoctorAvailability
 * @version 1.0.0
 */
export default class DoctorAvailability {
  /**
   * Constructs a new <code>DoctorAvailability</code>.
   * Графік роботи лікаря
   * @alias module:model/DoctorAvailability
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DoctorAvailability</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DoctorAvailability} obj Optional instance to populate.
   * @return {module:model/DoctorAvailability} The populated <code>DoctorAvailability</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DoctorAvailability();
      if (data.hasOwnProperty('day'))
        obj.day = ApiClient.convertToType(data['day'], 'String');
      if (data.hasOwnProperty('start_time'))
        obj.startTime = ApiClient.convertToType(data['start_time'], 'String');
      if (data.hasOwnProperty('end_time'))
        obj.endTime = ApiClient.convertToType(data['end_time'], 'String');
    }
    return obj;
  }
}

/**
 * День тижня
 * @member {String} day
 */
DoctorAvailability.prototype.day = undefined;

/**
 * Час початку прийому
 * @member {String} startTime
 */
DoctorAvailability.prototype.startTime = undefined;

/**
 * Час закінчення прийому
 * @member {String} endTime
 */
DoctorAvailability.prototype.endTime = undefined;

