/*
 * Medical System API
 * API для управління лікарями та записами на прийом у медичній системі.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MedicalSystemApi);
  }
}(this, function(expect, MedicalSystemApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Doctor', function() {
      beforeEach(function() {
        instance = new MedicalSystemApi.Doctor();
      });

      it('should create an instance of Doctor', function() {
        // TODO: update the code to test Doctor
        expect(instance).to.be.a(MedicalSystemApi.Doctor);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property speciality (base name: "speciality")', function() {
        // TODO: update the code to test the property speciality
        expect(instance).to.have.property('speciality');
        // expect(instance.speciality).to.be(expectedValueLiteral);
      });

      it('should have the property contactInfo (base name: "contact_info")', function() {
        // TODO: update the code to test the property contactInfo
        expect(instance).to.have.property('contactInfo');
        // expect(instance.contactInfo).to.be(expectedValueLiteral);
      });

      it('should have the property availability (base name: "availability")', function() {
        // TODO: update the code to test the property availability
        expect(instance).to.have.property('availability');
        // expect(instance.availability).to.be(expectedValueLiteral);
      });

      it('should have the property education (base name: "education")', function() {
        // TODO: update the code to test the property education
        expect(instance).to.have.property('education');
        // expect(instance.education).to.be(expectedValueLiteral);
      });

      it('should have the property certificates (base name: "certificates")', function() {
        // TODO: update the code to test the property certificates
        expect(instance).to.have.property('certificates');
        // expect(instance.certificates).to.be(expectedValueLiteral);
      });

    });
  });

}));
