/*
 * Medical System API
 * API для управління лікарями та записами на прийом у медичній системі.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.68
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import Appointment from './model/Appointment';
import Doctor from './model/Doctor';
import DoctorAvailability from './model/DoctorAvailability';
import DoctorContactInfo from './model/DoctorContactInfo';
import Error from './model/Error';
import InlineResponse200 from './model/InlineResponse200';
import DefaultApi from './api/DefaultApi';

/**
* API___________.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MedicalSystemApi = require('index'); // See note below*.
* var xxxSvc = new MedicalSystemApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MedicalSystemApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MedicalSystemApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MedicalSystemApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Appointment model constructor.
     * @property {module:model/Appointment}
     */
    Appointment,

    /**
     * The Doctor model constructor.
     * @property {module:model/Doctor}
     */
    Doctor,

    /**
     * The DoctorAvailability model constructor.
     * @property {module:model/DoctorAvailability}
     */
    DoctorAvailability,

    /**
     * The DoctorContactInfo model constructor.
     * @property {module:model/DoctorContactInfo}
     */
    DoctorContactInfo,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
